logging:
  level:
    au.com.rakesh: 'info'
    org.springframework: 'info'
    org.apache.http: 'info'
  file: 'logs/${spring.application.name}.log'
app:
  crawler:
    default-depth: 3
    max-depth-allowed: 5
    time-out: 5000
    follow-redirects: true

server:
  contextPath: /${spring.application.name}
  port: 8100

rest:
  response:
    error:
      debug: true

spring:
  application:
    name: 'web-crawler-service'
  jackson:
    default-property-inclusion: 'always'
    serialization:
      write_dates_as_timestamps: false
      indent_output: false
  cache:
    cache-names:
      - ${spring.application.name}
    caffeine.spec: 'maximumSize=5000,expireAfterWrite=86400s'
---

spring:
  profiles: development
  jackson:
    serialization.indent_output: true
logging:
  level:
    au.com.rakesh: 'debug'
---

spring:
  profiles: test

logging:
  pattern:
    file: '[%d{ISO8601}] [%thread] [%level] [%logger] [serviceName:${spring.application.name}] => %msg%n'
  level:
    au.com.rakesh: 'debug'
---

spring:
  profiles: production

logging:
  file: 'logs/${spring.application.name}.log'
  pattern:
    file: '[%d{ISO8601}] [%thread] [%level] [%logger] [serviceName:${spring.application.name}] => %msg%n'

rest:
  response:
    error:
      debug: false
---

spring:
  profiles: local
  jackson:
    serialization.indent_output: true
logging:
  level:
    au.com.rakesh: 'debug'
  pattern:
    console: '[%d{ISO8601}] [%thread] [%level] [%logger] [serviceName:${spring.application.name}] => %msg%n'
---
